name: Java CI with Maven

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B package --file e-shop-manager/pom.xml
      
    - name: Generate site JaCoCo
      run: cd e-shop-manager && mvn test jacoco:report
    
    - name: Coveralls Coverage Report Submission
      run: cd e-shop-manager && mvn coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
        
    - name: Generate site Checkstyle
      run: cd e-shop-manager && mvn clean && mvn -B checkstyle:checkstyle
    - uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: e-shop-manager/target/site/
        
      
        
